
### AUTH Login
# @name login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "andre-carlos@Live.com",
  "password": "123456"
}

### find

GET http://localhost:3000/status-tracker

### updated
POST http://localhost:3000/status-tracker
Content-Type: application/json
Authorization: Bearer {{login.response.body.accessToken}}

{
"statusHistory": [
      "watching",
      "watched",
      "paused",
      "abandoned"
    ]
}

### updated
PATCH http://localhost:3000/status-tracker/1
Content-Type: application/json

{
"statusHistory": [
      "reading",
      "completed",
      "paused",
      "abandoned"
    ]
}
