
### AUTH Login
# @name login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "eroshi@aros.com",
  "password": "123456"
}

### Create author
POST http://localhost:3000/author-content
Content-Type: application/json
Authorization: Bearer {{login.response.body.accessToken}}

{
    "name":"Masashi Kishimoto",
    "bio":"Japão",
    "awards": [],
    "genres": ["Gênio", "Avenutura", "Mistério"],
}

### GET one author
GET http://localhost:3000/author-content/1
Content-Type: application/json

### GET all authors
GET http://localhost:3000/author-content
Content-Type: application/json
Authorization: Bearer {{login.response.body.accessToken}}

### Update one author
PATCH http://localhost:3000/author-content/1
Content-Type: application/json
Authorization: Bearer {{login.response.body.accessToken}}

{
    "bestSellers": ["Banano"]
}

### DELETE one author
DELETE http://localhost:3000/author-content/3
Authorization: Bearer {{login.response.body.accessToken}}
Content-Type: application/json